# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: CouchDB
version: "1.0.0.20"
slug: couchdb
description: CouchDB database server for Home Assistant
url: "https://github.com/db1996/hassio-addons/tree/main/couchdb"
arch:
  - aarch64
  - amd64
init: false
apparmor: false
ports:
  5984/tcp: 5984
ports_description:
  5984/tcp: CouchDB HTTP interface
map:
  - config:rw
  - ssl
options:
  port: 5984
  username: "admin"
  password: null
schema:
  port: "int(1,65535)"
  username: "str"
  password: "password"
# image: "ghcr.io/home-assistant/{arch}-addon-couchdb"